import { db } from "../core/db.js";
import { el, toast, naira, fmtDate, modal, debounce, num } from "../core/utils.js";
import { card, pageHead, table, btn, input, select, field } from "../core/ui.js";
import { invoiceDoc } from "../core/documents.js";
import { previewHtml, downloadPdf, buildDocHtml, generatePdfBlob, shareDocumentToWhatsApp, PRINT_CSS } from "../core/print.js";
import { calculateInvoiceTotal, calculateTotalPaid } from "../core/calculations.js";
import { logActivity } from "../core/activity.js";
import { softDeleteInvoice, applyPayment } from "../core/billing.js";
import { can } from "../core/rbac.js";
import * as cfg from "../core/config.js";
import { editInvoiceFees } from "./students.js";

const statusTag = (s) => {
  const cls = s === "PAID" ? "green" : s === "PARTIALLY PAID" ? "orange" : "red";
  return `<span class="tag ${cls}">${s}</span>`;
};

function makePaymentModal(invoiceId, ctx, onComplete) {
  const inv = db.get("invoices", invoiceId);
  if (!inv || inv.balance <= 0) return toast("Invoice already fully paid.");

  const amtInp = input({ type: "number", value: inv.balance, style: "font-weight:bold; font-size:18px;" });
  
  const m = modal({
    title: `Receive Payment`,
    size: "sm",
    body: el("div", {}, [
      el("div", { style: "margin-bottom:12px; font-size:13px; color:var(--muted)" }, `Invoice: ${inv.invoiceNo} | Balance: ${naira(inv.balance)}`),
      field("Amount (₦)", amtInp)
    ]),
    footer: [
      btn("Submit Payment", {
        variant: "success",
        onclick: async () => {
          const amount = num(amtInp.value);
          if (amount <= 0 || amount > inv.balance) return toast("Invalid payment amount.", "error");
          try {
            await applyPayment(inv, { amount, cashier: ctx?.user?.name || "" });
            toast("Payment received successfully!", "success");
            m.close();
            if (typeof onComplete === "function") onComplete();
          } catch (err) {
            toast(err.message, "error");
          }
        }
      })
    ]
  });
}

// Summary Page generation
function generateSummaryPageHTML(invoices, title) {
  const account = cfg.schoolAccount ? cfg.schoolAccount() : {};
  const b = { schoolName: account.accountName || "CIC KANO" };
  const totalAmount = calculateInvoiceTotal(invoices);
  const totalPaid = calculateTotalPaid(invoices);
  const totalBalance = invoices.reduce((sum, inv) => sum + Number(inv.balance || 0), 0);
  
  return `
    <div class="a4-one-page" style="padding: 40px; display: flex; flex-direction: column; justify-content: center; align-items: center; height: 100%; text-align: center;">
      <h1 style="font-size: 32px; color: #123f7a; margin-bottom: 10px;">${b.schoolName || "CIC KANO"}</h1>
      <h2 style="font-size: 24px; color: #333; margin-bottom: 30px; text-transform: uppercase;">Bulk Invoice Print Summary</h2>
      
      <table style="width: 80%; max-width: 600px; margin: 0 auto; border-collapse: collapse; font-size: 18px; text-align: left;">
        <tr><th style="padding: 15px; border-bottom: 1px solid #ccc; width: 50%;">Print Job Profile</th><td style="padding: 15px; border-bottom: 1px solid #ccc;"><b>${title}</b></td></tr>
        <tr><th style="padding: 15px; border-bottom: 1px solid #ccc;">Date Printed</th><td style="padding: 15px; border-bottom: 1px solid #ccc;">${fmtDate(Date.now())}</td></tr>
        <tr><th style="padding: 15px; border-bottom: 1px solid #ccc;">Total Invoices</th><td style="padding: 15px; border-bottom: 1px solid #ccc; font-size: 24px;"><b>${invoices.length}</b></td></tr>
        <tr><th style="padding: 15px; border-bottom: 1px solid #ccc;">Unique Students</th><td style="padding: 15px; border-bottom: 1px solid #ccc;"><b>${new Set(invoices.map(i => i.studentId)).size}</b></td></tr>
        <tr><th style="padding: 15px; border-bottom: 1px solid #ccc;">Grand Total Value</th><td style="padding: 15px; border-bottom: 1px solid #ccc; color: #123f7a; font-size: 24px;"><b>${naira(totalAmount)}</b></td></tr>
        <tr><th style="padding: 15px; border-bottom: 1px solid #ccc;">Total Amount Paid</th><td style="padding: 15px; border-bottom: 1px solid #ccc; color: #207348;"><b>${naira(totalPaid)}</b></td></tr>
        <tr><th style="padding: 15px; border-bottom: 1px solid #ccc;">Total Outstanding Balance</th><td style="padding: 15px; border-bottom: 1px solid #ccc; color: #c0392b; font-size: 20px;"><b>${naira(totalBalance)}</b></td></tr>
      </table>
      <div style="margin-top: 50px; font-style: italic; color: #666;">Generated by KCIS Enterprise System</div>
    </div>
  `;
}

// Asynchronous batch renderer to prevent browser crash on 500+ invoices
async function renderInvoicesBatch(invoices, onProgress) {
  const htmlChunks = [];
  const batchSize = 25;
  for (let i = 0; i < invoices.length; i += batchSize) {
    const batch = invoices.slice(i, i + batchSize);
    
    // Yield to browser UI thread to keep it responsive
    await new Promise(res => setTimeout(res, 50));
    
    for (const inv of batch) {
      const student = db.get("students", inv.studentId);
      // Append the invoice wrapped in a page-break container
      htmlChunks.push(`<div class="invoice-page">${invoiceDoc(inv, student)}</div>`);
    }
    
    if (onProgress) onProgress(Math.min(i + batchSize, invoices.length), invoices.length);
  }
  return htmlChunks.join("");
}

export function showInvoice(invoiceId, { afterClose } = {}) {
  const inv = db.get("invoices", invoiceId);
  if (!inv) return toast("Invoice not found", "error");
  const student = db.get("students", inv.studentId);
  const html = invoiceDoc(inv, student);
  const body = el("div", {});
  const preview = el("div", { class: "doc-preview" });
  preview.innerHTML = `<style>${PRINT_CSS}</style><div class="doc a4-fit">${html}</div>`;
  body.appendChild(preview);
  const m = modal({
    title: `Invoice ${inv.invoiceNo}`, size: "lg", body, onClose: afterClose,
    footer: [
      btn("Print", { icon: "🖨️", onclick: () => previewHtml(html, { title: "Invoice " + inv.invoiceNo }) }),
      btn("Download PDF", { onclick: () => downloadPdf(html, { title: "Invoice " + inv.invoiceNo, filename: `Invoice_${inv.invoiceNo}.pdf` }) }),
      btn("WhatsApp", { variant: "success", onclick: () => {
        const phone = student?.parentPhone || student?.guardianPhone || "";
        shareDocumentToWhatsApp(html, { title: "Invoice " + inv.invoiceNo, filename: `Invoice_${inv.invoiceNo}.png`, phone });
      } }),
      btn("Close", { variant: "primary", onclick: () => m.close() })
    ]
  });
}

export function render(root, ctx) {
  if (ctx.param) { showInvoice(ctx.param); }
  root.appendChild(pageHead("Invoices", "Manage, filter, and bulk-print student invoices."));

  const isManager = can(ctx.user.role, "manageInvoices") || ["super_admin", "admin", "accountant"].includes((ctx.user.role || "").toLowerCase().replace(" ", "_"));

  const selectedIds = new Set();
  let currentRows = [];

  // Filters
  const search = input({ placeholder: "Search name, adm no, parent phone...", style: "flex:1" });
  const filterClass = select(() => [{ value: "", label: "All Classes" }, ...cfg.classes().map(c => ({ value: c.id, label: c.name }))]);
  const filterTerm = select(() => [{ value: "", label: "All Terms" }, ...(cfg.sessions().terms || ["First Term", "Second Term", "Third Term"]).map(t => ({ value: t, label: t }))]);
  const filterSession = select(() => [{ value: "", label: "All Sessions" }, ...(cfg.sessions().list || [cfg.currentSession()]).filter(Boolean).map(s => ({ value: s, label: s }))]);
  const filterStatus = select(() => [
    { value: "", label: "All Status" },
    { value: "UNPAID", label: "Unpaid" },
    { value: "PARTIALLY PAID", label: "Partially Paid" },
    { value: "PAID", label: "Fully Paid" }
  ]);
  const findDupBtn = btn("Find Duplicates", { variant: "warning", onclick: () => {
    search.value = "!duplicates";
    draw();
  } });

  const filterRow = el("div", { class: "row", style: "margin-bottom:14px; gap:8px; flex-wrap:wrap; align-items:center;" }, [
    search, filterClass, filterTerm, filterSession, filterStatus, findDupBtn
  ]);
  root.appendChild(filterRow);

  // Sticky Toolbar Wrapper
  const toolbarHost = el("div", { style: "position:sticky; top:10px; z-index:100; margin-bottom:14px;" });
  root.appendChild(toolbarHost);

  const host = el("div");
  root.appendChild(host);

  const executeBulkAction = (actionType, explicitInvoices = null, defaultTitle = "Bulk_Invoices") => {
    const targetInvoices = explicitInvoices || currentRows.filter(i => selectedIds.has(i.id));
    if (targetInvoices.length === 0) return toast("No invoices selected.", "warning");

    let statusType = "Safe";
    let statusColor = "var(--success)";
    if (targetInvoices.length > 100 && targetInvoices.length <= 300) {
      statusType = "Medium";
      statusColor = "var(--warning)";
      if (!confirm(`You are about to process ${targetInvoices.length} invoices. Continue?`)) return;
    } else if (targetInvoices.length > 300) {
      statusType = "Large Export";
      statusColor = "var(--danger)";
    }

    const totalVal = calculateInvoiceTotal(targetInvoices);
    const title = prompt("Enter Print Job Title / Filename:", defaultTitle) || defaultTitle;

    const body = el("div", { style: "text-align:center; padding: 20px;" }, [
      el("h3", { text: `Ready to process ${targetInvoices.length} invoices` }),
      el("p", { text: `Total Value: ${naira(totalVal)}` }),
      el("p", { style: `color: ${statusColor}; font-weight: bold;`, text: `Status: ${statusType}${statusType === "Large Export" ? " - This export may take several minutes." : ""}` }),
      el("div", { id: "bulk-progress", style: "margin-top: 20px; font-weight: bold; color: var(--primary);" }, [
        document.createTextNode("Waiting to start...")
      ])
    ]);

    const m = modal({ title: "Bulk Invoice Processor", body, footer: [
      btn("Start Processing", { variant: "primary", id: "bulk-start-btn", onclick: async (e) => {
        e.target.disabled = true;
        const prog = document.getElementById("bulk-progress");
        
        if (actionType === "print" || actionType === "pdf") {
            prog.textContent = "Rendering pages... (0%)";
            const summaryHtml = `<div class="invoice-page">${generateSummaryPageHTML(targetInvoices, title)}</div>`;
            const invoicesHtml = await renderInvoicesBatch(targetInvoices, (done, total) => {
              prog.textContent = `Rendering pages... (${Math.round((done/total)*100)}%) - ${done}/${total}`;
            });
            const fullHtml = summaryHtml + invoicesHtml;
            prog.textContent = "Loading Preview...";
            
            setTimeout(() => {
              m.close();
              const pm = modal({
                title: `Preview: ${title}`,
                size: "xl",
                body: el("div", { class: "doc-preview", style: "height: 65vh; overflow-y: auto; background: #525659; padding: 20px; border-radius: 4px;" }, [
                    el("div", { html: `<style>${PRINT_CSS}</style><div class="doc a4-fit" style="margin: 0 auto; min-height: 297mm;">${fullHtml}</div>` })
                ]),
                footer: [
                  btn("Confirm & Print", { variant: "primary", icon: "🖨️", onclick: () => {
                      printHtml(fullHtml, { title: title });
                      pm.close();
                  }}),
                  btn("Confirm & Download PDF", { variant: "success", onclick: () => {
                      downloadPdf(fullHtml, { title: title, filename: `${title.replace(/\s+/g, "_")}.pdf` });
                      pm.close();
                  }}),
                  btn("Cancel", { onclick: () => pm.close() })
                ]
              });
            }, 100);
            
        } else if (actionType === "zip" || actionType === "printshop") {
            prog.textContent = "Loading compression libraries...";
            if (!window.JSZip || !window.saveAs) {
                await Promise.all([
                    new Promise((res, rej) => { const s = document.createElement("script"); s.src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js"; s.onload = res; s.onerror = rej; document.head.appendChild(s); }),
                    new Promise((res, rej) => { const s = document.createElement("script"); s.src = "https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.5/FileSaver.min.js"; s.onload = res; s.onerror = rej; document.head.appendChild(s); })
                ]);
            }
            
            const zipCount = Math.ceil(targetInvoices.length / 500);
            
            for (let zipIdx = 0; zipIdx < zipCount; zipIdx++) {
                const zip = new window.JSZip();
                const chunk = targetInvoices.slice(zipIdx * 500, (zipIdx + 1) * 500);
                
                if (actionType === "printshop" && zipIdx === 0) {
                     const csv = "AdmissionNo,StudentName,Class,Term,Session,Total,Paid,Balance\n" + 
                         chunk.map(i => `"${i.admissionNo || ""}","${i.studentName || ""}","${cfg.className(i.classId) || ""}","${i.term || ""}","${i.session || ""}",${i.totalAmount || 0},${i.amountPaid || 0},${i.balance || 0}`).join("\n");
                     zip.file("Summary.csv", csv);
                     zip.file("PrintInstructions.txt", "Please print all PDFs in the Invoices folder. Each PDF is A4 and corresponds to one student.");
                }
                
                const rootFolder = zip.folder("Invoices");
                
                for (let i = 0; i < chunk.length; i++) {
                    const inv = chunk[i];
                    const student = db.get("students", inv.studentId);
                    const className = cfg.className(inv.classId) || "UnknownClass";
                    
                    prog.textContent = `[Part ${zipIdx+1}/${zipCount}] Generating PDF ${i+1}/${chunk.length}...`;
                    
                    const blob = await generatePdfBlob(invoiceDoc(inv, student), { title: `Invoice ${inv.invoiceNo}` });
                    
                    const sName = (inv.studentName || "Student").replace(/[^a-zA-Z0-9\s]/g, "").replace(/\s+/g, "_");
                    const sTerm = (inv.term || "Term").replace(/\s+/g, "");
                    const safeName = `${inv.admissionNo || "CICK"}_${sName}_${className.replace(/[^a-zA-Z0-9]/g, "")}_${sTerm}.pdf`;
                    
                    // Group by class folder
                    rootFolder.folder(className).file(safeName, blob);
                    
                    // Release memory, yield thread
                    await new Promise(r => setTimeout(r, 20)); 
                }
                
                prog.textContent = `[Part ${zipIdx+1}/${zipCount}] Compressing ZIP...`;
                const content = await zip.generateAsync({ type: "blob" });
                
                prog.textContent = `[Part ${zipIdx+1}/${zipCount}] Downloading...`;
                const outName = zipCount > 1 ? `${title}_Part${zipIdx+1}.zip` : `${title}.zip`;
                window.saveAs(content, outName);
            }
            m.close();
        }
      } }),
      btn("Cancel", { onclick: () => m.close() })
    ]});
  };

  const drawToolbar = () => {
    toolbarHost.innerHTML = "";
    if (selectedIds.size === 0 && !isManager) return;

    const totalValue = calculateInvoiceTotal(currentRows.filter(i => selectedIds.has(i.id)));

    const tb = el("div", { class: "card", style: "background: var(--primary); color: white; padding: 10px 15px; display: flex; align-items: center; justify-content: space-between; border-radius: 8px; box-shadow: 0 4px 12px rgba(0,0,0,0.15); flex-wrap:wrap; gap:10px;" }, [
      el("div", { style: "font-size: 16px; font-weight: bold;" }, [
        selectedIds.size > 0 
          ? document.createTextNode(`${selectedIds.size} Invoices Selected | Total: ${naira(totalValue)}`)
          : document.createTextNode(`Bulk Actions Available`)
      ]),
      el("div", { style: "display: flex; gap: 10px; flex-wrap:wrap;" }, [
        isManager ? btn("Select All", { variant: "light", onclick: () => selectionController.selectAll(currentRows.map(r => r.id)) }) : null,
        isManager && selectedIds.size > 0 ? btn("Deselect All", { variant: "light", onclick: () => { selectedIds.clear(); draw(); } }) : null,
        selectedIds.size > 0 ? btn("Download ZIP (Primary)", { variant: "success", onclick: () => executeBulkAction("zip", null, "Invoices_ZIP") }) : null,
        selectedIds.size > 0 ? btn("Combined PDF", { variant: "light", onclick: () => executeBulkAction("pdf", null, "Invoices_Combined") }) : null,
        selectedIds.size > 0 ? btn("Print All", { variant: "light", onclick: () => executeBulkAction("print", null, "Bulk_Invoices_Print") }) : null,
        selectedIds.size > 0 ? btn("Print Unpaid", { variant: "warning", onclick: () => {
          const unpaid = currentRows.filter(i => selectedIds.has(i.id) && i.status === "UNPAID");
          if (!unpaid.length) return toast("No unpaid invoices in selection.", "error");
          executeBulkAction("print", unpaid, "Selected_Unpaid_Invoices");
        } }) : null,
        isManager && selectedIds.size > 0 ? btn("Delete Selected", { variant: "danger", onclick: async () => {
          if (!selectedIds.size) return;
          const ids = Array.from(selectedIds);
          const totalValue = calculateInvoiceTotal(ids.map(id => db.get("invoices", id)));
          const conf = prompt(`You are about to permanently delete ${ids.length} selected invoices (Value: ${naira(totalValue)}). Type DELETE to confirm:`);
          if (conf !== "DELETE") return toast("Deletion cancelled.", "error");
          for (let id of ids) await softDeleteInvoice(id, ctx.user.email);
          selectedIds.clear();
          toast(`Deleted ${ids.length} invoices.`, "success");
          draw();
        }}) : null,
        isManager ? btn("Mass Delete By Filter", { variant: "danger", onclick: async () => {
          if (!currentRows.length) return toast("No invoices in current filter.");
          const totalValue = calculateInvoiceTotal(currentRows);
          const conf = prompt(`You are about to delete all ${currentRows.length} filtered invoices (Total Value: ${naira(totalValue)}). Type DELETE to continue:`);
          if (conf !== "DELETE") return toast("Mass deletion cancelled.", "error");
          for (let row of currentRows) await softDeleteInvoice(row.id, ctx.user.email);
          selectedIds.clear();
          toast(`Mass deleted ${currentRows.length} invoices.`, "success");
          draw();
        }}) : null,
        isManager ? btn("Sync Student Programs", { variant: "secondary", onclick: () => {
          if (!confirm("This will scan all invoices and update student program enrollments automatically. Continue?")) return;
          const students = db.list("students");
          const invoices = db.list("invoices");
          let updated = 0;
          for (const s of students) {
            let changed = false;
            const ids = new Set(s.programIds || []);
            const invs = invoices.filter(i => i.studentId === s.id);
            for (const inv of invs) {
              for (const svc of (inv.services || [])) {
                if (svc.programId && !ids.has(svc.programId)) { ids.add(svc.programId); changed = true; }
                else if (svc.name) {
                  const svcNameStr = svc.name.toLowerCase().trim();
                  const allP = cfg.programs({ activeOnly: false, session: "", term: "" });
                  const p = allP.find(x => {
                    const pn = x.name.toLowerCase().trim();
                    return svcNameStr === pn || svcNameStr === pn + " program fee" || svcNameStr === pn + " program";
                  });
                  if (p && !ids.has(p.id)) { ids.add(p.id); changed = true; }
                }
              }
            }
            if (changed) {
              s.programIds = [...ids];
              s.programs = s.programIds;
              s.programNames = s.programIds.map(id => cfg.programName(id));
              db.save("students", s);
              updated++;
            }
          }
          toast(`Synced programs for ${updated} existing students from their invoices.`, "success");
        }}) : null,
        selectedIds.size > 0 ? btn("Clear", { variant: "danger", onclick: () => { selectedIds.clear(); draw(); } }) : null
      ])
    ]);
    toolbarHost.appendChild(tb);
  };

  // Quick Action Buttons
  if (isManager) {
    const quickActions = card("Quick Bulk Print Tools", [
      el("div", { class: "row", style: "gap:10px; flex-wrap:wrap;" }, [
        btn("Download Complete ZIP Archive", { variant: "success", onclick: () => {
          if (!currentRows.length) return toast("No invoices found.");
          executeBulkAction("zip", currentRows, "Complete_Invoices_Archive");
        }}),
        btn("Export For Print Shop", { variant: "primary", onclick: () => {
          if (!currentRows.length) return toast("No invoices found.");
          executeBulkAction("printshop", currentRows, "PRINT_PACKAGE");
        }}),
        btn("Print Outstanding Invoices", { variant: "danger", onclick: () => {
          const unpaid = db.list("invoices").filter(i => i.status === "UNPAID");
          if (!unpaid.length) return toast("No unpaid invoices found.");
          executeBulkAction("zip", unpaid, "Outstanding_Invoices");
        }}),
        btn("Print Part-Payment", { variant: "warning", onclick: () => {
          const partial = db.list("invoices").filter(i => i.status === "PARTIALLY PAID");
          if (!partial.length) return toast("No partially paid invoices found.");
          executeBulkAction("zip", partial, "Partially_Paid_Invoices");
        }}),

        (can(ctx.user.role, "deleteRecords") || ["Super Admin", "Admin"].includes(ctx.user.role)) ? btn("Mass Delete By Filter", { variant: "danger", onclick: async () => {
          if (!currentRows.length) return toast("No invoices in current filter.");
          const totalValue = calculateInvoiceTotal(currentRows);
          const conf = prompt(`You are about to delete all ${currentRows.length} filtered invoices (Total Value: ${naira(totalValue)}). Type DELETE to continue:`);
          if (conf !== "DELETE") return toast("Mass deletion cancelled.", "error");
          for (let row of currentRows) await softDeleteInvoice(row.id, ctx.user.email);
          selectedIds.clear();
          toast(`Mass deleted ${currentRows.length} invoices.`, "success");
          draw();
        }}) : null
      ])
    ]);
    root.appendChild(quickActions);
  }

  const selectionController = {
    has: (id) => selectedIds.has(id),
    selectAll: (ids) => { ids.forEach(id => selectedIds.add(id)); draw(); },
    clear: () => { selectedIds.clear(); draw(); },
    toggle: (id) => { if (selectedIds.has(id)) selectedIds.delete(id); else selectedIds.add(id); draw(); }
  };

  const draw = () => {
    const q = (search.value || "").toLowerCase();
    const cId = filterClass.value;
    const term = filterTerm.value;
    const sess = filterSession.value;
    const stat = filterStatus.value;

    let rows = db.list("invoices").sort((a, b) => b.createdAt - a.createdAt);

    if (q === "!duplicates") {
      const grouped = {};
      const duplicates = new Set();
      rows.forEach(i => {
        if (!i.studentId || !i.term || !i.session) return;
        const total = i.totalAmount || 0;
        const key = `${i.studentId}_${i.term}_${i.session}_${total}`;
        if (!grouped[key]) grouped[key] = [];
        grouped[key].push(i);
      });
      Object.values(grouped).forEach(grp => {
        if (grp.length > 1) {
          grp.forEach(i => duplicates.add(i.id));
        }
      });
      rows = rows.filter(i => duplicates.has(i.id));
      if (rows.length === 0) toast("No duplicate invoices found.", "success");
    } else {
      rows = rows.filter(i => {
        // Basic text search including parent phone and class
        if (q) {
          const student = db.get("students", i.studentId);
          const parentPhone = student ? (student.parentPhone || "").toLowerCase() : "";
          const className = cfg.className(i.classId || "").toLowerCase();
          const matchText = `${i.studentName} ${i.invoiceNo} ${i.admissionNo} ${parentPhone} ${className}`.toLowerCase();
          if (!matchText.includes(q)) return false;
        }
        if (cId && i.classId !== cId) return false;
        if (term && i.term !== term) return false;
        if (sess && i.session !== sess) return false;
        if (stat && i.status !== stat && !(stat === "UNPAID" && !i.status)) return false;
        return true;
      });
    }

    currentRows = rows;
    host.innerHTML = "";
    
    // Purge selectedIds that are no longer in DB
    const validIds = new Set(db.list("invoices").map(i => i.id));
    for (const id of selectedIds) { if (!validIds.has(id)) selectedIds.delete(id); }

    const displayRows = rows.slice(0, 100);

    // Provide the currently displayed ids to table selection controller so Select All only applies to filtered ones
    const currentIds = currentRows.map(r => r.id);
    const boundSelectionController = {
        ...selectionController,
        selectAll: () => selectionController.selectAll(currentIds)
    };

    const emptyMsg = rows.length > 100 ? `Showing 100 of ${rows.length} invoices. Use filters to narrow down.` : "No invoices match the current filters.";

    host.appendChild(card("", [
      rows.length > 100 ? el("div", { style: "padding:10px; background:#eef2ff; color:#4f46e5; border-radius:4px; margin-bottom:10px; text-align:center; font-weight:bold;" }, `Showing latest 100 of ${rows.length} invoices. Use Search or Filters to find specific records.`) : el("span"),
      table([
      { label: "Invoice No", key: "invoiceNo" },
      { label: "Student", key: "studentName" },
      { label: "Class", render: (i) => cfg.className(i.classId) },
      { label: "Term", render: (i) => `${i.term} ${i.session}` },
      { label: "Total", align: "right", render: (i) => naira(i.totalAmount) },
      { label: "Balance", align: "right", render: (i) => naira(i.balance) },
      { label: "Status", html: true, render: (i) => statusTag(i.status) },
      { label: "Date", render: (i) => fmtDate(i.createdAt) },
      { label: "", render: (i) => el("div", { class: "row", style: "gap: 5px;" }, [
        btn("View", { sm: true, onclick: () => showInvoice(i.id) }),
        btn("Edit", { sm: true, variant: "ghost", onclick: () => editInvoiceFees(i.id, ctx, draw) }),
        i.balance > 0 ? btn("Pay", { sm: true, variant: "success", onclick: () => makePaymentModal(i.id, ctx, draw) }) : null,
        isManager ? btn("\u2715", { sm: true, variant: "danger", onclick: async () => {
          if (confirm("You are about to permanently delete this record. Continue?")) {
            await softDeleteInvoice(i.id, ctx.user.email);
            selectedIds.delete(i.id);
            toast("Invoice deleted.", "success");
            draw();
          }
        }}) : null
      ]) }
    ], displayRows, { empty: emptyMsg, selection: isManager ? boundSelectionController : null })]));

    drawToolbar();
  };

  draw();
  [filterClass, filterTerm, filterSession, filterStatus].forEach(el => el.onchange = draw);
  search.oninput = debounce(draw, 200);

  const off = db.on("invoices", draw);
  return () => off();
}

